# Play 1: Install and enable required software
- name: Install & enable required software
  hosts: web
  remote_user: azureuser
  become: yes

  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

# Play 2: Deploy mini finance website
- name: Deploy Mini Finance website
  hosts: web
  remote_user: azureuser
  become: yes

  tasks:
    - name: Clone Mini Finance website repo
      git:
        repo: https://github.com/pravinmishraaws/mini_finance.git
        dest: /tmp/mini_finance
        force: yes

    - name: Copy website content to Nginx web root
      copy:
        src: /tmp/mini_finance/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes

# Play 3: Configure Nginx to serve the site
- name: Configure Nginx to serve the site
  hosts: web
  remote_user: azureuser
  become: yes

  tasks:
    - name: Overwrite the default Nginx configuration file
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.html;

              location / {
                  try_files $uri $uri/ /index.html;
              }

              error_page 404 /index.html;
          }
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted

